### ISSUE TITLE
Getting "There is no started application" exception on Java Play.

### ISSUE THREAD

**Issue by alex-vas** [matiwinnetou/swagger-play24#8]
I seems to be getting "RuntimeException: There is no started application" exception in application startup.

```
[Server] $ run

--- (Running the application, auto-reloading is enabled) ---

[info] p.a.l.c.ActorSystemProvider - Starting application default Akka system: application
[info] p.c.s.NettyServer - Listening for HTTP on /0:0:0:0:0:0:0:0:9000

(Server started, use Ctrl+D to stop and go back to the console...)

## Adding specific configuration: application-dev.conf
2015-08-10 10:48:27,285 INFO  p.a.l.c.ActorSystemProvider >> Starting application default Akka system: application
2015-08-10 10:48:27,346 WARN  swagger >> ControllerScanner - looking for controllers with API annotation
2015-08-10 10:48:27,473 ERROR application >>

! @6n4k0mcl0 - Internal server error, for (GET) [/] ->

play.api.UnexpectedException: Unexpected exception[ExceptionInInitializerError: null]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:169) ~[play-server_2.11-2.4.2.jar:2.4.2]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1$$anonfun$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.2.jar:2.4.2]
        at scala.Option.map(Option.scala:146) ~[scala-library-2.11.6.jar:na]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:121) ~[play-server_2.11-2.4.2.jar:2.4.2]
        at play.core.server.DevServerStart$$anonfun$mainDev$1$$anon$1$$anonfun$get$1$$anonfun$apply$1.apply(DevServerStart.scala:119) ~[play-server_2.11-2.4.2.jar:2.4.2]
Caused by: java.lang.ExceptionInInitializerError: null
        at java.lang.Class.forName0(Native Method) ~[na:1.8.0_45]
        at java.lang.Class.forName(Class.java:348) ~[na:1.8.0_45]
        at com.wordnik.swagger.core.SwaggerContext$.loadClass(SwaggerContext.scala:21) ~[swagger-core_2.11-1.3.12.jar:1.3.12]
        at pl.matisoft.swagger.PlayApiScanner$$anonfun$classes$1.applyOrElse(PlayApiScanner.scala:52) ~[swagger-play24_2.11-1.4.jar:1.4]
        at pl.matisoft.swagger.PlayApiScanner$$anonfun$classes$1.applyOrElse(PlayApiScanner.scala:49) ~[swagger-play24_2.11-1.4.jar:1.4]
Caused by: java.lang.RuntimeException: There is no started application
        at scala.sys.package$.error(package.scala:27) ~[scala-library-2.11.6.jar:na]
        at play.api.Play$$anonfun$current$1.apply(Play.scala:71) ~[play_2.11-2.4.2.jar:2.4.2]
        at play.api.Play$$anonfun$current$1.apply(Play.scala:71) ~[play_2.11-2.4.2.jar:2.4.2]
        at scala.Option.getOrElse(Option.scala:121) ~[scala-library-2.11.6.jar:na]
        at play.api.Play$.current(Play.scala:71) ~[play_2.11-2.4.2.jar:2.4.2]
```

**Comment by matiwinnetou** [comment]
This is not an issue with the module, I am running this module successfully on both Java and Scala versions. Please make sure you are correctly setting up a Play app.
